name: Docker Build

on:
  push:
    branches:
      - main
      - development
  pull_request:
    branches:
      - main
      - development

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'corretto'
          cache: 'gradle'

      - name: Get version from build.gradle
        id: get-version
        run: |
          echo "VERSION=$(grep 'version' build.gradle | awk -F '[ =]' '{print $3}')" >> $GITHUB_ENV


      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      - name: Build Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          push: false
          tags: |
            ${{ github.repository }}:${{ env.VERSION }}
            ${{ github.repository }}:${{ env.VERSION }}-RC
