name: Docker Build

on:
  push:
    branches:
      - main
      - development
  pull_request:
    branches:
      - main
      - development

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distributio: 'corretto'
          cache: 'gradle'

      - name: Get version from build.gradle
        id: get-version
        run: echo "::set-output name=version::$(grep 'version' build.gradle | awk -F '[ =]' '{print $3}')"

      - name: Set up Docker
        uses: docker/setup-buildx-action@v1

      - name: Build Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: false
          tags: |
            ${{ github.repository }}:${{ steps.get-version.outputs.version }}
            ${{ github.repository }}:${{ steps.get-version.outputs.version }}-RC
