name: Docker Build

on:
  push:
    branches:
      - main
      - development
  pull_request:
    types:
      -closed
    branches:
      - main
      - development  

jobs:
  validation:
    name: "Validation"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: gradle/wrapper-validation-action@v1

  test_build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'corretto'

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Execute Gradle build
        run: ./gradlew build

  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Get version from build.gradle
        id: get-version
        run: echo "VERSION=$(grep -oP "version\s*=\s*'\K[^']+" build.gradle)" >> $GITHUB_ENV
        
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker
        uses: docker/setup-buildx-action@v2
        
      - name: Login to Docker Hub
        run: |
          docker login -u "${{ secrets.NEXUS_USER }}" -p "${{ secrets.NEXUS_PASSWORD }}" nexus.edpn.io
          
      - name: Build Docker image
        run: |
          docker buildx build --push --tagelitedangerouspilotnetwork/backend-eddn-message-listener:${{ env.VERSION }}
